name: asset-transfer-benchmark
description: 'Performance test for Asset Transfer Basic chaincode using Go'
workers:
  type: local
  number: 5
rounds:
  - label: Create Asset
    description: Benchmark round for creating new assets on the ledger (Write).
    txDuration: 30
    rateControl:
      type: fixed-rate
      opts:
        tps: 50
    workload:
      module: ../workload/createAsset.js
      arguments:
        assets: 10000
        contractId: basic
  
  - label: Read Asset
    description: Benchmark round for querying a single asset by ID (Read).
    txDuration: 30
    rateControl:
      type: fixed-rate
      opts:
        tps: 100
    workload:
      module: ../workload/readAsset.js
      arguments:
        assets: 10000
        contractId: basic
  
  - label: Update Asset
    description: Benchmark round for updating an existing asset (Write).
    txDuration: 30
    rateControl:
      type: fixed-rate
      opts:
        tps: 30
    workload:
      module: ../workload/updateAsset.js
      arguments:
        assets: 10000
        contractId: basic
  
  - label: Query All Assets
    description: Benchmark round for querying all assets on the ledger (Read All).
    txDuration: 30
    rateControl:
      type: fixed-rate
      opts:
        tps: 20
    workload:
      module: ../workload/queryAllAssets.js
      arguments:
        contractId: basic
